title: Malia Ulfa
email: mel.malia028@gmail.com
description: A personal blog by Malia Ulfa, a student at Politeknik Negeri Lhokseumawe. 
              This blog is built using Jekyll and hosted on GitHub Pages. The content is primarily in Indonesian, but some posts may be in English.
url: 'https://maliaulfa2.github.io/'

plugins: 
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag